services:
  backend:
    build: ./backend
    container_name: projeto_cartao_backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  mysql:
    image: mysql:8.0
    container_name: projeto_cartao_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  frontend:
    image: nginx:alpine
    container_name: projeto_cartao_frontend
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./script.js:/usr/share/nginx/html/script.js:ro
      - ./script:/usr/share/nginx/html/script:ro
      - ./estilizacao:/usr/share/nginx/html/estilizacao:ro
    depends_on:
      - backend
volumes:
  mysql_data:
